### ISSUE TITLE
Some assets are crashing the game

### ISSUE THREAD

**Issue by xXoanon** [WILLATRONIX/Community-Blueprint-Pack#1]
Especially the ones from the medieval pack, I've found 2 or 3 that crash the game.

**Comment by xXoanon** [comment]
The one I can remember right now is "medieval_windmill_45deg.bp" that crashes the game when trying to place, but there are others.

**Comment by WILLATRONIX** [comment]
its a compatibility issue with older blueprints and it's not the easiest thing to fix. This is because of mojang changing grass to short_grass
